# Generated by Django 2.2.20 on 2022-02-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('bounty', models.DecimalField(decimal_places=7, max_digits=20)),
                ('summary', models.TextField(blank=True, max_length=400)),
                ('description', models.TextField(max_length=4000)),
                ('title', models.TextField(max_length=50)),
            ],
        ),
    ]
