# Generated by Django 2.2.20 on 2022-02-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='bounty',
            new_name='questBounty',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='questDesc',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='questName',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='questSummary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='username',
        ),
    ]
