# Generated by Django 2.2.20 on 2022-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_auto_20220220_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='questBounty',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='questDesc',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='questSummary',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
