# Generated by Django 2.2.20 on 2022-02-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_auto_20220220_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='questBounty',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
