# Generated by Django 2.2.20 on 2022-02-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_auto_20220220_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='questBounty',
            field=models.TextField(default=0.1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='questDesc',
            field=models.TextField(default='testDesc', max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='questSummary',
            field=models.TextField(default='summary', max_length=400),
            preserve_default=False,
        ),
    ]
