# Generated by Django 2.2.20 on 2022-02-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_auto_20220220_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidcode', models.TextField(max_length=400)),
                ('completedCode', models.TextField(max_length=25000)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='inputs',
            field=models.TextField(default=[], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='outputs',
            field=models.TextField(default='[]', max_length=100),
            preserve_default=False,
        ),
    ]
